apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: itmo
spec:
  cidr: 192.168.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: company == "itmo"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: itmo2
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: company == "itmo2"
